version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ksekret"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      nx-dependencies:
        patterns:
          - "@nx/*"
        update-types:
          - "minor"
          - "patch"
      react-dependencies:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      nestjs-dependencies:
        patterns:
          - "@nestjs/*"
        update-types:
          - "minor"
          - "patch"
      testing-dependencies:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "playwright*"
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"