all:
  children:
    k3s_cluster:
      children:
        k3s_servers:
          hosts:
            k3s-master:
              ansible_host: 31.57.109.65
              ansible_user: root
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
        k3s_agents:
          hosts:
            # Add additional worker nodes here if needed
            # k3s-worker-1:
            #   ansible_host: WORKER_IP_ADDRESS
            #   ansible_user: root
      vars:
        # K3s configuration variables
        k3s_version: v1.28.3+k3s2
        k3s_token: "{{ vault_k3s_token | default('change-me-please') }}"
        k3s_server_location: /var/lib/rancher/k3s
        k3s_config_file: /etc/rancher/k3s/k3s.yaml
        k3s_service_env:
          K3S_KUBECONFIG_MODE: "644"
        # Disable certain components if needed
        k3s_disable_components:
          - traefik  # Use if you want to install your own ingress controller
          # - servicelb
          # - local-storage
