---
# K3s cluster configuration variables

# K3s version to install
k3s_version: v1.28.3+k3s2

# K3s installation options
k3s_config:
  write-kubeconfig-mode: "644"
  cluster-init: true
  disable:
    - traefik  # Disable default traefik ingress controller
    # - servicelb  # Disable default load balancer
    # - local-storage  # Disable default local storage

# Environment variables for K3s service
k3s_service_env:
  K3S_KUBECONFIG_MODE: "644"

# Network configuration
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"

# Additional K3s server arguments
k3s_server_args:
  - "--cluster-cidr={{ k3s_cluster_cidr }}"
  - "--service-cidr={{ k3s_service_cidr }}"
  - "--write-kubeconfig-mode=644"

# Additional K3s agent arguments  
k3s_agent_args: []

# System configuration
disable_firewall: true
update_system: true

# Required system packages
required_packages:
  - curl
  - wget
  - unzip
  - tar
