---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: homeaccounting-dev
  labels:
    app: frontend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # Build image locally: docker build -f frontend/Dockerfile -t homeaccounting-frontend:dev .
        image: homeaccounting-frontend:dev
        imagePullPolicy: Never # Use local image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-src
          mountPath: /app/frontend/src
        - name: shared-src
          mountPath: /app/shared/src
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: frontend-src
        hostPath:
          path: /Users/ksekret/projects/homeaccounting/frontend/src
          type: Directory
      - name: shared-src
        hostPath:
          path: /Users/ksekret/projects/homeaccounting/shared/src
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: homeaccounting-dev
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
